import { LEFT, MAIN, RIGHT } from './fixed-types.js';

const TABLE_CLASS = 'wenv-table-05';
const TABLE_WRAPPER_CLASS = `${TABLE_CLASS}-wrapper`;
const LEFT_CLASS = `${TABLE_CLASS}-${LEFT}`;
const MAIN_CLASS = `${TABLE_CLASS}-${MAIN}`;
const RIGHT_CLASS = `${TABLE_CLASS}-${RIGHT}`;
const BODY_CLASS = `${TABLE_CLASS}-body`;
const BODY_ROW_CLASS = `${TABLE_CLASS}-body-row`;
const BODY_ROW_HIGHLIGHT_CLASS = `${TABLE_CLASS}-row-highlight`;
const BODY_ROW_HIGHLIGHT_BAR_CLASS = `${TABLE_CLASS}-row-highlight-bar`;
const BODY_ROWS_WRAPPER_CLASS = `${TABLE_CLASS}-body-rows-wrapper`;
const BODY_CELL_CLASS = `${TABLE_CLASS}-body-row-cell`;
const BODY_SELECTION_CLASS = `${TABLE_CLASS}-body-selection`;
const BODY_CELL_TEXT_CLASS = `${TABLE_CLASS}-body-row-cell-text`;
const HEAD_CLASS = `${TABLE_CLASS}-head`;
const HEAD_CELL_CLASS = `${TABLE_CLASS}-head-cell`;
const HEAD_SELECTION_CLASS = `${TABLE_CLASS}-head-selection`;
const HEAD_TITLE_CLASS = `${TABLE_CLASS}-head-cell-title`;
const HEAD_SORT_CLASS = `${TABLE_CLASS}-head-cell-title-sort`;
const HEAD_CHILDREN_CLASS = `${TABLE_CLASS}-head-cell-children`;
export {
  TABLE_WRAPPER_CLASS,
  TABLE_CLASS,
  LEFT_CLASS,
  MAIN_CLASS,
  RIGHT_CLASS,
  HEAD_CLASS,
  HEAD_CELL_CLASS,
  HEAD_SELECTION_CLASS,
  HEAD_TITLE_CLASS,
  HEAD_SORT_CLASS,
  HEAD_CHILDREN_CLASS,
  BODY_CLASS,
  BODY_ROW_CLASS,
  BODY_ROW_HIGHLIGHT_CLASS,
  BODY_ROW_HIGHLIGHT_BAR_CLASS,
  BODY_ROWS_WRAPPER_CLASS,
  BODY_CELL_CLASS,
  BODY_SELECTION_CLASS,
  BODY_CELL_TEXT_CLASS,
};
